/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nayro
 */
public class DeleteLibrarian extends javax.swing.JFrame {

    ArrayList<Librarian> Librarians = new ArrayList(); //array list of librarians for deleting records

    public void readFileLibrariansDelete() throws FileNotFoundException {
        File librarianFile = new File("Librarians.txt");
        Scanner s = new Scanner(librarianFile); //read from file
        while (s.hasNextLine()) {//test file did ot reach its end
            String x = s.nextLine();
            String toks[] = x.split(","); //file is csv
            Librarian newL = new Librarian(toks[0], toks[1], toks[2], toks[3], toks[4], toks[5], toks[6]); //creates new librarian 
            Librarians.add(newL); //add to array list
        }
    }

    public void writeFileLibrariansDelete() throws FileNotFoundException {
        File flibrarian = new File("Librarian.txt");
        PrintWriter x = new PrintWriter(flibrarian);
        for (int i = 0; i < Librarians.size(); i++) {
            x.println(Librarians.get(i).getID() + "," + Librarians.get(i).getName() + "," + Librarians.get(i).getPassword() + "," + Librarians.get(i).getEmail() + "," + Librarians.get(i).getAddress() + "," + Librarians.get(i).getCity() + "," + Librarians.get(i).getContactNumber());
        }
        x.close();
    }

    /**
     * Creates new form DeleteLibrarian
     */
    public DeleteLibrarian() throws FileNotFoundException {
        initComponents();
        readFileLibrariansDelete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        idDelete = new javax.swing.JTextField();
        deleteDeleteLib = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Delete Librarian");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        deleteDeleteLib.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteDeleteLib.setText("Delete");
        deleteDeleteLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDeleteLibActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(deleteDeleteLib, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(deleteDeleteLib, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        AdminSection x = new AdminSection();
        x.setVisible(true); //return to the admin section
        this.hide();
    }//GEN-LAST:event_backActionPerformed

    private void deleteDeleteLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDeleteLibActionPerformed
        String id = idDelete.getText();
        //get fields to test for 
        boolean ErrorFlag = false, Found = false, EmptyFlag = false;
        if (id.isEmpty()) { //check if all fields are filled in
            EmptyFlag = true;
            JOptionPane.showMessageDialog(this, "one of the fields is empty, please try again");
        }
        if (!EmptyFlag) {
            if (id.charAt(0) == ' ') { //check all fields start with space
                JOptionPane.showMessageDialog(this, "The input must ot start with space, please try again");
                ErrorFlag = true;
            }
            for (int i = 0; i < id.length(); i++) {
                char c = id.charAt(i);
                if (!Character.isDigit(c)) { //check the name is all characters 
                    JOptionPane.showMessageDialog(this, "The name is invalid, please try again");
                    ErrorFlag = true;
                    break;
                }
            }

            if (!ErrorFlag) { //if no errors

                for (int i = 0; i < Librarians.size(); i++) {
                    if (Librarians.get(i).getID().equals(id)) { //check that the username and password exist
                        Librarians.remove(i); //delete from array list
                        Found = true;
                        JOptionPane.showMessageDialog(this, "Librarian deleted successfully");
                        try {
                            writeFileLibrariansDelete();
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(DeleteLibrarian.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        AdminSection xy = new AdminSection();
                        xy.setVisible(true);
                        this.hide();
                        break;
                    }
                }
                if (!Found) { //librarian not found
                    JOptionPane.showMessageDialog(this, "The Librarian is not found, please try again");
                }
            }
        }


    }//GEN-LAST:event_deleteDeleteLibActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DeleteLibrarian().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DeleteLibrarian.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton deleteDeleteLib;
    private javax.swing.JTextField idDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
