/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.io.File;
import java.io.FileNotFoundException;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static project2.StudentLogin.studentNameLogin;

/**
 *
 * @author nayro
 */
public class ViewIssuedBooksStudent extends javax.swing.JFrame {

    ArrayList<IssuedBook> IssuedBooks = new ArrayList();
    ArrayList<Book> Books = new ArrayList();

    /**
     * Creates new form ViewIssuedBooksStudent
     */
    public void readFileIssuedBooks() throws FileNotFoundException {
        File fBook = new File("IssuedBooks.txt");
        Scanner s = new Scanner(fBook); //read from the file
        while (s.hasNextLine()) { //checks file did not reach its end
            String x = s.nextLine();
            String toks[] = x.split(","); //file is csv
            IssuedBook newIB = new IssuedBook(toks[0], toks[1], toks[2], toks[3], toks[4]); //create new librarian with scanned fields using split
            IssuedBooks.add(newIB);
        }
    }

    public void readFileBooks() throws FileNotFoundException {
        File fBook = new File("Books.txt");
        Scanner s = new Scanner(fBook); //read from file
        while (s.hasNextLine()) { //checks file did not reach its end
            String x = s.nextLine();
            String toks[] = x.split(","); //file is csv
            int quan = parseInt(toks[5]);
            int ID = parseInt(toks[0]);
            int IssueCount = parseInt(toks[6]);
            Book newB = new Book(ID, toks[1], toks[2], toks[3], toks[4], quan, IssueCount, toks[7]); //create new librarian with scanned fields using split
            Books.add(newB);
        }
    }
    DefaultTableModel layout;

    public void takeData() {

        for (int i = 0; i < IssuedBooks.size(); i++) {
            for (int j = 0; j < Books.size(); j++) {
                String containerCallNo = "";
                if (studentNameLogin.equals(IssuedBooks.get(i).getStudentName())) {
                    containerCallNo = IssuedBooks.get(i).getBookCallNo();
                    if (containerCallNo.equals(Books.get(j).getCallNo())) {

                        layout.insertRow(layout.getRowCount(), new Object[]{i + 1, Books.get(j).getName(), IssuedBooks.get(i).getIssuedate(), IssuedBooks.get(i).getReturnDate()});
                        break;
                    }
                }
            }
        }
    }

    public ViewIssuedBooksStudent() throws FileNotFoundException {
        initComponents();
        readFileIssuedBooks();
        readFileBooks();
        layout = (DefaultTableModel) tableIssuedBooksStudent.getModel();
        takeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIssuedBooksStudent = new javax.swing.JTable();
        backIssued = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Issued Books");

        tableIssuedBooksStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "IssueDate", "ReturnDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableIssuedBooksStudent);

        backIssued.setText("back");
        backIssued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backIssuedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backIssued))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(backIssued)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backIssuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backIssuedActionPerformed
        StudentSection x = new StudentSection();
        x.setVisible(true);
        this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_backIssuedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewIssuedBooksStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewIssuedBooksStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewIssuedBooksStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewIssuedBooksStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewIssuedBooksStudent().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ViewIssuedBooksStudent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backIssued;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableIssuedBooksStudent;
    // End of variables declaration//GEN-END:variables
}
